### ISSUE TITLE
Sciview window hangs when tracing multiple paths from SNT

### ISSUE THREAD

**Issue by carshadi** [scenerygraphics/sciview#215] opened 2019-08-03 18:46 UTC
Starting Sciview from SNT, then tracing one path in SNT successfully displays the path in the Sciview window. However, tracing a second path causes Sciview to hang. The console shows this error: [ERROR] Call to vkAllocateDescriptorSets failed: A device memory allocation has failed.
![image](https://user-images.githubusercontent.com/44130022/62415781-55105d80-b5fd-11e9-874c-794c807337c0.png)

**Comment by carshadi** [comment] 2019-08-03 18:48
I have a GTX 1080 dedicated GPU, but the issue also occurred on my work pc which has a GTX Titan X

**Comment by tferr** [comment] 2019-08-14 11:18
@carshadi, can you please try this build (you will have to unzip it), and see if the hang still persists?

[Simple_Neurite_Tracer-3.1.99-SNAPSHOT.zip](https://github.com/scenerygraphics/sciview/files/3501057/Simple_Neurite_Tracer-3.1.99-SNAPSHOT.zip)

(It has the changes discussed in [SNT#55](https://github.com/fiji/Simple_Neurite_Tracer/issues/55))

**Comment by carshadi** [comment] 2019-08-14 15:09
it works!

**Comment by tferr** [comment] 2019-08-14 20:31
Thanks. here seems to be working also! @kephale , @skalarproduktraum, you can go ahead and close this issue.

**Closed** 2019-08-14 20:59 UTC

**Comment by skalarproduktraum** [comment] 2019-08-16 14:50
As a note for the future: when something like `[ERROR] Call to vkAllocateDescriptorSets failed: A device memory allocation has failed.` that's only the symptom of a problem, but not the root cause. 

If you can reproduce the error, it'd be super-helpful for us to get a debug log, which you can activate by setting the system property `scenery.LogLevel` to `debug`, e.g. by giving `-Dscenery.LogLevel=debug` on the command line when starting Fiji 👍

**Comment by carshadi** [comment] 2019-08-16 14:55
can do!
