### ISSUE TITLE
Edit -> Settings -> SciView problems:

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/sciview#357] opened 2021-02-08 09:49 UTC
- wrong name of the menu item (should be sciview)
- does nothing at all (used to control the old inspector + REPL panel)

I would remove this item completely.

**Comment by kephale** [comment] 2023-06-10 14:10
I think this is a duplicate of https://github.com/scenerygraphics/sciview/issues/284

**Closed by kephale** 2023-06-10 14:10 UTC
Labels: 1.0.0
