### ISSUE TITLE
SciJava command dialogs hang when (closing them?) on OS X

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#138] opened 2018-10-11 03:11 UTC
This appears to be OS X specific:

1. Start SciView, and run a demo like Volume Render
2. It might be placing the volume in a bad location, so Edit>Toggle floor, then View>Center on active node)
3. Change the Lut. (View>Set LUT)
4. If setting the LUT works, try again. Eventually it will hang indefinitely after pressing "OK"

I cannot replicate this on Ubuntu, but I and others are observing this on OS X.

**Comment by skalarproduktraum** [comment] 2018-10-14 16:52
Confirmed, seems to be a JavaFX-Swing interop issue. Tentatively fixed in scenerygraphics/scenery#219.

**Comment by skalarproduktraum** [comment] 2018-10-20 16:14
Fixed in #141.

**Closed by skalarproduktraum** 2018-10-20 16:14 UTC
Labels: bug, confirmed
