### ISSUE TITLE
Two detectable rendering/scene graph bugs in segmentation demo

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#301] opened 2020-11-07 08:50 UTC
![SegmentationDemo2bugs](https://user-images.githubusercontent.com/400105/98436781-84562a00-20de-11eb-8a5f-8e5702c1819f.gif)

1. you'll notice that the meshes rotate with the camera, this doesnt make sense. This is particularly bad for the spot in the bottom right that isn't even round, yet it still rotates.
2. the volume seems to clip out as you rotate to the other side

@skalarproduktraum I suspect these are upstream (but that is my favorite type of suspicion :D)

**Comment by skalarproduktraum** [comment] 2020-11-10 17:59
1. is not an upstream issue, but one caused by the marching cubes algo putting out CW triangle winding order while scenery expects CCW. This is fixed in 46bec9c by introducing the flipWindingOrder flag in MeshConverter, which is true by default, as it's mostly used for marching cube'd meshes.

2. is indeed an upstream issue that recently got introduced. Fixing it atm.

**Comment by skalarproduktraum** [comment] 2020-11-11 16:46
2. is fixed in https://github.com/scenerygraphics/scenery/pull/344 👍

**Closed** 2020-11-23 18:07 UTC
Labels: bug, confirmed
