### ISSUE TITLE
SciJava Commands fail silently

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#494] opened 2023-06-15 11:17 UTC
I've noticed this with a couple of bugs recently:

- the error that led to https://github.com/scenerygraphics/sciview/pull/493 was a silent crash in the CREMI demo
- when working on https://github.com/scenerygraphics/sciview/issues/234 during development I broke SetLUT, but when testing I can't get the error to display

I'll ask @ctrueden for help when he gets the chance. This seems to be a general issue with running Commands and their exceptions not being shown.

**Comment by kephale** [comment] 2023-06-15 11:57
I think one of the issues here is an example of a silently failing command: https://github.com/scenerygraphics/sciview/issues/438

**Comment by moreApi** [comment] 2023-06-15 13:53
In https://github.com/scenerygraphics/sciview/issues/477 Curtis mentioned https://github.com/scijava/scijava-common/issues/452 as a cause for this issue

**Comment by kephale** [comment] 2023-06-16 14:42
We could potentially catch these ourselves with this strategy: https://github.com/scijava/scijava-common/issues/452#issuecomment-1594719448

**Comment by kephale** [comment] 2023-07-20 19:56
1 would pull up the console and show the error?
2 would be prettier, but maybe 1 is sufficient and possibly less intrusive... 

My vote is for consistency with Fiji (which I think might be 1?)

**Comment by ctrueden** [comment] 2023-07-21 06:58
After digging into this issue again today for a while, I confirmed that the problem is actually already fixed, with the behavior of (1). However, when running in IntelliJ IDEA, it seems to be snarfing up the stderr and putting it only into its own log window, such that it no longer appears in the SciJava Console window. At least that's my theory. I'll be doing more testing tomorrow in an actual Fiji app outside of IntelliJ, so I'll be able to confirm for sure then. I'll wait to close this until I'm sure all is well, though.

**Comment by ctrueden** [comment] 2023-07-21 23:42
All right, confirmed, scijava/scijava-common#459 *does* fix this issue. I forced a sciview command to throw a `RuntimeException`, and then I see it now on both the actual console and the in SciJava graphical console window. :+1:

**Closed by ctrueden** 2023-07-21 23:42 UTC
Labels: 1.0.0
